package org.ironworkschurch.analytics.to

data class FlatPersonDetails (
  val uid: Int,
  val mail: String,
  val updated: String,
  val fname: String,
  val preferredName: String,
  val lname: String,
  val male: Int,
  val secondaryEmail: String,
  val rfidtag: String,
  val rfidtagAlt: String,
  val phoneHome: String,
  val phoneCell: String,
  val phoneWork: String,
  val address: String,
  val city: String,
  val state: String,
  val zipcode: String,
  val country: String?,
  val addressStartDate: String?,
  val addressEndDate: String?,
  val addressLabel: String?,
  val address2: String?,
  val city2: String?,
  val state2: String?,
  val zipcode2: String?,
  val country2: String?,
  val address2StartDate: String?,
  val address2EndDate: String?,
  val address2Label: String?,
  val dateBirth: String,
  val dateBaptism: String,
  val dateDied: String,
  val date1: String,
  val envNum: Int,
  val hasPicture: Boolean,
  val name: String,
  val canEdit: Boolean,
  val canEditPicture: Boolean,
  val canEditAllFields: Boolean,
  val hasUnApprovedChanges: Boolean
)

data class PersonGroup (
  val uid: Int,
  val gid: Int,
  val name: String
)

data class GroupHeader (
  val gid: Int,
  val name: String,
  val individual: Boolean,
  val selfCheckin: Boolean,
  val childCheckin: Boolean,
  val description: String,
  val address: String,
  val city: String,
  val state: String,
  val zipcode: String,
  val lat: Int,
  val lon: Int,
  val selfAdd: Boolean,
  val selfRequest: Boolean,
  val meetingDay: String,
  val meetingTime: String,
  val maxSize: Int,
  val active: Boolean,
  val visibleMembership: Boolean,
  val checkinChildLabelCnt: Int,
  val checkinGuardianLabelCnt: Int
)