create table if not exists PERSON_HEADER_DELTA
(
  did int AUTO_INCREMENT PRIMARY KEY ,
	uid int not null,
	active bit not null,
	address text null,
	address2 text null,
	address2EndDate text null,
	address2Label text null,
	address2StartDate text null,
	addressEndDate text null,
	addressLabel text null,
	addressStartDate text null,
	checkAccountNumberHash text null,
	checkRoutingNumberHash text null,
	checkinNote text null,
	city text null,
	city2 text null,
	country text null,
	country2 text null,
	date1 text null,
	date10 text null,
	date2 text null,
	date3 text null,
	date4 text null,
	date5 text null,
	date6 text null,
	date7 text null,
	date8 text null,
	date9 text null,
	dateBaptism text null,
	dateBirth text null,
	dateDied text null,
	dateJoined text null,
	envNum int not null,
	fname text null,
	hasPicture bit not null,
	inactiveDate text null,
	joinDate text null,
	lname text null,
	maddress text null,
	mail text null,
	male int not null,
	mcity text null,
	mcountry text null,
	mstate text null,
	mzipcode text null,
	phoneCell text null,
	phoneHome text null,
	phoneWork text null,
	pname text null,
	preferredName text null,
	raddress text null,
	rcity text null,
	rcountry text null,
	rfidtag text null,
	rfidtagAlt text null,
	rstate text null,
	rzipcode text null,
	secondaryEmail text null,
	state text null,
	state2 text null,
	text1 text null,
	text10 text null,
	text11 text null,
	text12 text null,
	text13 text null,
	text14 text null,
	text15 text null,
	text2 text null,
	text3 text null,
	text4 text null,
	text5 text null,
	text6 text null,
	text7 text null,
	text8 text null,
	text9 text null,
	timeLastAttended text null,
	timeLastTouched text null,
	zipcode text null,
	zipcode2 text null,
	ROW_EFF_DTS datetime default CURRENT_TIMESTAMP not null,
	ROW_EXP_DTS datetime null,
	CURR_ROW_FL varchar(1) default 'Y' not null,
	LAST_UPDATE_DTS datetime default CURRENT_TIMESTAMP not null,
  UNIQUE KEY bus_key (uid, ROW_EFF_DTS)
)