version: '3'
services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "iwc_members"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - discovery.type=single-node
      - transport.host=0.0.0.0
      - http.host=0.0.0.0
      - network.host=0.0.0.0
      - network.bind_host=0
      - discovery.zen.minimum_master_nodes=1
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.1
    ports:
      - 5601:5601
